name: "522-project"

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy<2
  - ipykernel
  - pandas
  - scikit-learn
  - altair
  - vl-convert-python
  - pyarrow
  - ucimlrepo
  - jupyterlab
  - pip
  - pip:
      - vegafusion
      - pointblank
      - deepchecks
      - anywidget
      - ipywidgets
  

